/*
Copyright (C) 1997-2001 Id Software, Inc.
Copyright (C) 2000-2002 Mr. Hyde and Mad Dog

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.

*/

// G:\quake2\baseq2\models/monsters/brain

// This file generated by ModelGen - Do NOT Modify

#define FRAME_walk101         	0
#define FRAME_walk102         	1
#define FRAME_walk103         	2
#define FRAME_walk104         	3
#define FRAME_walk105         	4
#define FRAME_walk106         	5
#define FRAME_walk107         	6
#define FRAME_walk108         	7
#define FRAME_walk109         	8
#define FRAME_walk110         	9

#define FRAME_run101         	1
#define FRAME_run102         	3
#define FRAME_run103         	5
#define FRAME_run104         	7
#define FRAME_run105         	9

#define FRAME_attak201         	10
#define FRAME_attak202         	11
#define FRAME_attak203         	12
#define FRAME_attak204         	13
#define FRAME_attak205         	14
#define FRAME_attak206         	15
#define FRAME_attak207         	16
#define FRAME_attak208         	17
#define FRAME_attak209         	18
#define FRAME_attak210         	19
#define FRAME_attak211         	20
#define FRAME_attak212         	21
#define FRAME_attak213         	22
#define FRAME_attak214         	23

#define FRAME_attak101         	24
#define FRAME_attak102        	25
#define FRAME_attak103         	26
#define FRAME_attak104         	27
#define FRAME_attak105         	28
#define FRAME_attak106         	29
#define FRAME_attak107         	30
#define FRAME_attak108         	31
#define FRAME_attak109         	32
#define FRAME_attak110         	33

#define FRAME_stand01         	34
#define FRAME_stand02         	35
#define FRAME_stand03         	36
#define FRAME_stand04         	37
#define FRAME_stand05         	38
#define FRAME_stand06         	39
#define FRAME_stand07         	40
#define FRAME_stand08         	41
#define FRAME_stand09         	42
#define FRAME_stand10         	43
#define FRAME_stand11         	44
#define FRAME_stand12         	45
#define FRAME_stand13         	46
#define FRAME_stand14         	47
#define FRAME_stand15         	48
#define FRAME_stand16         	49
#define FRAME_stand17         	50
#define FRAME_stand18         	51
#define FRAME_stand19         	52
#define FRAME_stand20         	53
#define FRAME_stand21         	54
#define FRAME_stand22         	55
#define FRAME_stand23         	56
#define FRAME_stand24         	57
#define FRAME_stand25         	58
#define FRAME_stand26         	59
#define FRAME_stand27         	60
#define FRAME_stand28         	61
#define FRAME_stand29         	62
#define FRAME_stand30         	63
#define FRAME_stand31         	64
#define FRAME_stand32         	65
#define FRAME_stand33         	66
#define FRAME_stand34         	67
#define FRAME_stand35         	68
#define FRAME_stand36         	69
#define FRAME_stand37         	70
#define FRAME_stand38         	71
#define FRAME_stand39         	72
#define FRAME_stand40         	73
#define FRAME_stand41         	74
#define FRAME_stand42         	75
#define FRAME_stand43         	76
#define FRAME_stand44         	77
#define FRAME_stand45         	78
#define FRAME_stand46         	79
#define FRAME_stand47         	80
#define FRAME_stand48         	81
#define FRAME_stand49         	82
#define FRAME_stand50         	83
#define FRAME_stand51         	84
#define FRAME_stand52         	85
#define FRAME_stand53         	86
#define FRAME_stand54         	87
#define FRAME_stand55         	88
#define FRAME_stand56         	89
#define FRAME_stand57         	90
#define FRAME_stand58         	91
#define FRAME_stand59         	92
#define FRAME_stand60         	93

#define FRAME_duck01          	94
#define FRAME_duck02          	95
#define FRAME_duck03          	96
#define FRAME_duck04          	97
#define FRAME_duck05          	98
#define FRAME_duck06          	99
#define FRAME_defens01        	100
#define FRAME_defens02        	101
#define FRAME_defens03        	102
#define FRAME_defens04        	103
#define FRAME_defens05        	104
#define FRAME_defens06        	105

#define FRAME_pain101         	106
#define FRAME_pain102         	107
#define FRAME_pain103         	108
#define FRAME_pain104         	109
#define FRAME_pain105         	110
#define FRAME_pain106         	111
#define FRAME_pain201         	112
#define FRAME_pain202         	113
#define FRAME_pain203         	114
#define FRAME_pain204         	115
#define FRAME_pain205         	116
#define FRAME_pain206         	117
#define FRAME_pain301         	118
#define FRAME_pain302         	119
#define FRAME_pain303         	120
#define FRAME_pain304         	121
#define FRAME_pain305         	122
#define FRAME_pain306         	123

#define FRAME_death101         	106
#define FRAME_death102         	107
#define FRAME_death103         	108

#define FRAME_death201         	112
#define FRAME_death202         	113
#define FRAME_death203         	114

#define MODEL_SCALE		1.000000
